[package]
name = "elv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal = "0.2.1"
num-traits = "0.2.15"
num-bigint = "0.4.3"
unicode-width = "0.1.10"
